# Generated by Django 4.0.3 on 2022-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
