# Generated by Django 4.0.3 on 2022-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_video_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
