# Generated by Django 4.0.3 on 2022-03-27 18:50

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_video_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to=base.models.video_directory_path),
        ),
    ]
