# Generated by Django 4.0.3 on 2022-03-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_video_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
