# Generated by Django 4.0.3 on 2022-03-30 19:51

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_video_title_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(default='/static/no-profile/no-profile.jpg', null=True, upload_to=base.models.profile_directory_path),
        ),
    ]
