# Generated by Django 4.0.3 on 2022-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_comment_dislikes_remove_reply_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
