# Generated by Django 4.0.3 on 2022-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_channel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
