# Generated by Django 4.0.3 on 2022-03-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_channel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
